name: test-build

on: [push, pull_request]

jobs:
  lint:
    name: Lint files
    runs-on: ubuntu-latest
    environment:
      name: linting-env
    steps:
      - name: Checkout
        uses: actions/checkout@4
      - name: Lint - Black
        uses: psf/black@stable